import Header from "./components/Header/Header";
import MoscowLogo from "./components/MoscowLogo";
import Footer from "./components/Footer";
import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MoscowLogo />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
